version: '3.7'

services:
  mysql:
    container_name: musicas-mysql
    image: inf21dw2g003/musicas-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      # schema?
    networks:
      - musicas-network
    ports:
      - 3306:3306

  app:
    depends_on:
      - mysql
    container_name: musicas-app
    image: inf21dw2g003/musicas-app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - musicas-network

  react:
    depends_on:
      - app
    container_name: musicas-react
    image: inf21dw2g003/musicas-react:latest
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - musicas-network

networks:
  musicas-network:
