version: '3.7'

services:
  react:
    depends_on:
      - app
    container_name: musicas-react
    image: musicas-react
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - musicas-network

networks:
  musicas-network: