version: '3.7'

services:
  mysql:
    container_name: musicas-mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_PASSWORD: 12345678
    volumes:
      - musicas-mysql-data:/var/lib/mysql
    networks:
      - musicas-network
    ports:
      - 3306:3306


  app:
    depends_on:
      - mysql
    container_name: musicas-app
    build:
      context: .
      dockerfile: dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DB: musicas
    ports:
      - 3000:3000
    networks:
      - musicas-network

networks:
  musicas-network:

volumes:
  musicas-mysql-data:

